### ISSUE TITLE
null value not handled gracefully in ToJson()

### ISSUE THREAD

**Issue by the1plummie** [LitJSON/litjson#12]
Following code result in an error

```
    string json_str = @"{
        ""name""  : ""Bill"",
        ""age""   : 32,
        ""awake"" : true,
        ""n""     : 1994.0226,
        ""note""  : [ ""life"", ""is"", ""but"", ""a"", ""dream"" ],
        ""null_str"" : null
      }";


    JsonData json = JsonMapper.ToObject(json_str);
    Console.WriteLine(json.ToJson());
```

NullReferenceException: Object reference not set to an instance of an object
LitJson.JsonData.WriteJson (IJsonWrapper obj, LitJson.JsonWriter writer) (at Assets/LitJson/JsonData.cs:795)
LitJson.JsonData.WriteJson (IJsonWrapper obj, LitJson.JsonWriter writer) (at Assets/LitJson/JsonData.cs:840)
LitJson.JsonData.ToJson () (at Assets/LitJson/JsonData.cs:972)

**Comment by corbinyo** [comment]
Still not working
