### ISSUE TITLE
Serialization includes extra garbage in MonoAndroid10 build

### ISSUE THREAD

**Issue by bluemonkmn** [LitJSON/litjson#71]
See https://stackoverflow.com/questions/48272476/extra-garbage-produced-by-litjson-serialization-with-aws-sdk-for-monoandroid10 for details.
When I use litJson from AWSSDK.Core.3.3.19.1\lib\MonoAndroid10\AWSSDK.Core.dll the serialized output includes extra fields like "&lt;Name&gt;k__BackingField":"William Shakespeare". I don't understand why this only affects the MonoAndroid10 build -- it's not clear whether it's an AWSSDK build issue or a LitJSON build issue or if the different builds have different code, making it potentially a code issue.

**Comment by bluemonkmn** [comment]
This bug has also been reported at https://github.com/aws/aws-sdk-net/issues/837 which is probably the more appropriate place to report this since the problem cannot be reproduced in the stand-alone component.

**Comment by devlead** [comment]
Ok👍
