### ISSUE TITLE
unable to find repository origin with: dotnet sourcelink-git origin

### ISSUE THREAD

**Issue by DrPoldo** [LitJSON/litjson#77]
Hi,
I can't select the target framework and I can't build the project. I don't know if this issue is related to vs2017 or with this project and i'm pretty new to sourcelink too.

![litjson](https://user-images.githubusercontent.com/99696/36421278-26624004-1638-11e8-8c69-15e754b993a0.png)

Whenever i try to build the project i've always get:
unable to find repository origin with: dotnet sourcelink-git origin

![litjson-ps-build](https://user-images.githubusercontent.com/99696/36421553-2d1558e0-1639-11e8-9291-a5ad0067365a.png)

**Comment by devlead** [comment]
@DrPoldo as the assembly targets multiple frameworks Visual Studio currently won't let you pick a framework but you have edit csproj manually if you want to add a framework
```xml
    <TargetFrameworks>netstandard2.0;net45;netstandard1.5;net40;net35;net20</TargetFrameworks>
```

Are you running from your cloned fork och have you cloned the main repository?

**Comment by DrPoldo** [comment]
ok, problem solved, as you suggested i've edited the csproj file as follow:

`  <PropertyGroup>
    <TargetFramework>net45</TargetFramework>	<TargetFrameworks>netstandard2.0;net45;netstandard1.5;net40;net35;net20</TargetFrameworks>
  </PropertyGroup>`

As a side note, previously i was using v0.12.0, the one that i successfully compiled is the last commit, i didn't try the change on v0.12.0.

Thanks a lot
